### PR TITLE
Fp-api with "with-*" pattern

### PR DESCRIPTION
**Pull request by jamil7**
Qrizzly's request is here!

Here's a short example: 

```

    let store = new SqlStreamStore.InMemoryStreamStore()

    let caseMessages =
        SController.init store "Case::1"
        |> With.prefetch
        |> With.messageCount 200
        |> With.readVersion ReadVersion.Any
        |> SMessage.messages

```

Can be found [here](https://github.com/jamil7/SQLStreamStore.FSharp/blob/fc8cc0b38df7fb15d4f2f6f98804019fff247087/src/SController.fs#L76)

### CODE REVIEW

**Comment by Mousaka** [comment]
Not sure why With as a module was needed but.. Looks good =)

**Comment by jamil7** [comment]
> Not sure why With as a module was needed but.. Looks good =)

To know which optional params you can supply. Keeping them in with makes it easy to dot-discover the options that you have. 

Hmm dot-discover I like this word.. I should use it more often🤣

**Comment by roetlich** [comment]
Question from a C# perspective:
You have classes in which *every* method is abstract, should you use interfaces instead? Not sure about the implications in F#.

**Comment by jamil7** [comment]
> Question from a C# perspective:
> You have classes in which _every_ method is abstract, should you use interfaces instead? Not sure about the implications in F#.

I'm using those as interfaces :P Basically I didn't spend much time to learn how interfaces work in F#. There are some weird parts. Abstract classes however, worked as I anticipated right away, and I'm using them as a way to define an interface rather than lift up functionality as one would normally do.

If I end up using the FP approach all of those files will disappear anyways :P

**Comment by roetlich** [comment]
Abstract classes are more limited, you can only implement one class at a time etc. If they "disappear anyways" it doesn't matter, otherwise interface are better

**Pull request closed without merging**
