### PR TITLE
Complete redesign

### PR DESCRIPTION
**Pull request by jamil7**
### Logic behind this design

- Functional style is nice, but not always the best approach
- Every operation to a stream need at least 4 dependencies 2 of which can be default, but in FP style None must be supplied the whole time
- Operations on the streams' messages require cumbersome async fetching of a ReadPage object, and to get the JsonData another async op is required. By having a class that encapsulates the repeated logic a much nicer API emerges.

### CODE REVIEW

**Comment by Mousaka** [comment]
```
let caseOne = StreamController(store, "case::1")
caseOne.messages(prefetch = true).filter(fun msg -> msg.Type = "ClaimCreated").getJsonData()
```
An alternative FP-style using the ["with*" pattern ](https://youtu.be/PDyWP-0H4Zo?t=1471)(difficult to google and probably has another name somewhere)
```
streamControllerInit store "case::1"
|> withPrefetch
|> withFilter (fun msg -> msg.Type = "ClaimCreated")
|> asJson
```
### Pros
- Gives all the nice things (like sensible defaults and forcing you to provide required fields) but stays in the FP-world
### Cons
Can't think of any right now :P 

What do you think?

**Comment by jamil7** [comment]
> An alternative FP-style using the "with*" pattern (difficult to google and probably has another name somewhere)

> Gives all the nice things (like sensible defaults and forcing you to provide required fields) but stays in the FP-world

This is definitely a nice alternative had the base code been written to support it. I don't see a way to use this easily in this specific instance.

Here's an example 

```
override this.isEnd(?readDirection: ReadDirection, ?readVersion: ReadVersion, ?messageCount: int, ?prefetch: bool) =
         let readDirection' =
             defaultArg readDirection ReadDirection.Forward

         let readVersion' = defaultArg readVersion ReadVersion.Any
         let messageCount' = defaultArg messageCount 1000
         let prefetch' = defaultArg prefetch false

 
          asyncResult {
             let! readPage = streamReadMatcher readDirection' prefetch' store stream readVersion' messageCount'
             return readPage.IsEnd
         }
```

For `isEnd` to work it needs the 4 params. They are optional in the sense that there are sensible defaults for them. Now the problem with the "with*-pattern" is that the first call will call `streamReadMatcher` with default arguments directly, and when piping to set another value other that the default one, another call must be done to `streamReadMatcher` with the new parameters. 

To make this work I need to build an expression parser that looks at the whole call, and passes in optionals :P 
It might be also doable with `lazy`, but it will only complicate things...
I would love to hear from you if you can think of a possible, less complicated implementation :D 


Side thought: 

> Gives all the nice things (like sensible defaults and forcing you to provide required fields) **but stays in the FP-world**

IMHO `caseOne.messages(prefetch = true).filter(fun msg -> msg.Type = "ClaimCreated").getJsonData()` is in the FP-world, only with dots instead of pipes symbols, it's more like F#/Elm FP-style vs. idk something like Scala/Java/C#/.. FP-style.

**Comment by Mousaka** [comment]
I think in this pattern you usualy divide the API into terminating and nonterminating functions. In the video example the terminating call is `toHtml` after that you can't pipe to any other `with*` calls. The same principles usually applies in the OO languages as well for example:
```
         Stream<Integer> stream = list.stream();
         Integer[] evenNumbersArr = stream.filter(i -> i%2 == 0).toArray(Integer[]::new); // toArray is terminating giving your actual result
```
. So in our case `getJsonData()` is terminating and it is only then any calls to StreamStore should be made if possible.
Isn't isEnd just a boolean on the page? Maybe I'm missing something.
And yes I think you build it using a lot of Option wrapped arguments internally :P

**Comment by jamil7** [comment]
> So in our case getJsonData() is terminating

Hmm I see you point. Yes it should be perfectly doable just not within the confines of the original library. So basically I have to redefine a lot of stuff and pass around a ton of internal Options just like you said.

> **Cons** Can't think of any right now :P

The biggest con with this approach is worsened discoverability. This is a problem with pure FP generally, and not specific to a language. A type can't have functions related it to it, the same way an object has methods related to it. F# is very nice in this aspect as it allows type extensions. 

The point here is, if we follow this with*-pattern we won't be able to know what options we have if we don't look at some doc or implementation details (in the case of none existent docs). While in the dotted version you get help from the editor, which shows all the parameters that we can supply. 

IMHO I think since this code is made to be a blackbox it would benefit from better discoverability. All what the user needs to know is that a StreamController is needed to work with streams, and everything else is just an editor hint away (through suggestion, and dotting into objects).

**Comment by Mousaka** [comment]
I think it can be exactly as discoverable as the OO version. The module exposes all the with* functions so the editor should suggest those in the same way.

**Comment by jamil7** [comment]
> I think it can be exactly as discoverable as the OO version. The module exposes all the with* functions so the editor should suggest those in the same way.

The module can expose functions, but you don't get feedback on what functions can be used when, for example, typing 
`streamControllerInit store "Case::1" |> withPrefetch` the pipe passes the `init` function to `withPrefetch`, but how would you know that `withPrefetch` exists to begin with (if you can't see the source code)? The editor won't help you at all, contrary to the dotted syntax way (call it OOP if you want to :P) where you will get a list of all available methods the second you type a dot.

**Comment by Mousaka** [comment]
image

**Comment by Mousaka** [comment]
It's true that it does not expose them when only pressing `.` which is annoying but it gives suggestions when you start typing which I think is okay. I wonder if new fsharp version provided better ways of packaging libraries to get better editor tooling.

**Comment by jamil7** [comment]
Yeah I see what you mean, but then `withPrefetch`, and all other optional params has to be in a module called `OptionalParams` or something, and each call would look this: 
```
streamControllerInit store "case::1"
|> OptionalParams.withPrefetch
|> OptionalParams.withFilter (fun msg -> msg.Type = "ClaimCreated")
|> ResultingMessage?.asJson()
```
I mean it works, but idk why this would a better pick. It's definitely more verbose, and you still need to remember 2 extra module names.

**Comment by Mousaka** [comment]
Wouldn't you usually either use the Read or Append modules? If they expose their own "with*" functions and terminating functions as their API I think that could be a nice API and you wouldn't need more than one module at a time.
```f#
Read.init store "case::1"
|> Read.withPrefretch
|> Read.withFilter
|> Read.asJson
```
and if you wanted you could open Read and get this to be less verbose.

Sure it's a bit more verbose but I think it's ok. I still think it's a better pick because it does not have any drawbacks as I can see so far but doing the OO-pattern has a slight drawback of mixing styles from the users perspective and it makes the source code more difficult to read for anyone not good at classes in F# (me included)

**Comment by jamil7** [comment]
I'll make a little experiment, and see how it turns out. 🤓

Side note:
F# classes "feel" more like types, than actual classes TBH. It's just like defining a type and some functions with the `member` keyword instead of let 🙂

**Pull request closed without merging**
